# Generated by Django 3.2.9 on 2022-04-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technicalrecord',
            old_name='user',
            new_name='player',
        ),
    ]
