# Generated by Django 4.0.4 on 2022-04-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_alter_player_date_created_alter_player_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='technicalrecord',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
