# Generated by Django 4.0.4 on 2022-04-30 15:55

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_alter_technicalrecord_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='date_created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='dob',
            field=django_jalali.db.models.jDateField(),
        ),
        migrations.AlterField(
            model_name='technicalrecord',
            name='date_created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True),
        ),
    ]
