# Generated by Django 4.0.4 on 2022-04-30 15:56

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_alter_player_date_created_alter_player_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='date_created',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='technicalrecord',
            name='date_created',
            field=django_jalali.db.models.jDateField(auto_now_add=True),
        ),
    ]
