# Generated by Django 4.0.4 on 2022-05-19 15:17

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0011_alter_player_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('date_created', django_jalali.db.models.jDateField(auto_now_add=True)),
                ('staff_type', models.CharField(choices=[(1, 'Coach'), (2, 'Trainer')], default=1, max_length=2)),
            ],
        ),
    ]
