# Generated by Django 4.0.4 on 2022-05-19 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalrecord',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.staff'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('1', 'Coach'), ('2', 'Trainer')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='technicalrecord',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.player'),
        ),
    ]
