# Generated by Django 4.0.4 on 2022-05-19 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_technicalrecord_staff_alter_staff_staff_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalrecord',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='analysis.staff'),
        ),
    ]
