# Generated by Django 4.0.4 on 2022-05-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0014_alter_technicalrecord_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalrecord',
            name='class_duration',
            field=models.FloatField(default=1),
        ),
    ]
