# Generated by Django 4.0.4 on 2022-05-19 16:22

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0015_technicalrecord_class_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='last_payment',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
