# Generated by Django 4.0.4 on 2022-05-19 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0017_payment_remove_staff_last_payment_staff_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='analysis.payment'),
        ),
    ]
