# Generated by Django 4.0.4 on 2022-05-19 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0018_alter_staff_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analysis.staff'),
        ),
    ]
