# Generated by Django 4.0.4 on 2022-05-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0023_alter_physicalrecord_attention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalrecord',
            name='class_duration',
            field=models.FloatField(default=1),
        ),
    ]
