# Generated by Django 4.0.4 on 2022-05-24 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0024_physicalrecord_class_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments', to='analysis.staff'),
        ),
    ]
