# Generated by Django 4.0.4 on 2022-05-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0025_alter_payment_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalrecord',
            name='player',
        ),
        migrations.AddField(
            model_name='technicalrecord',
            name='player',
            field=models.ManyToManyField(related_name='players', to='analysis.player'),
        ),
    ]
