# Generated by Django 4.0.4 on 2022-06-04 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0029_remove_physicalrecord_class_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
