# Generated by Django 4.0.4 on 2022-06-05 05:21

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0031_alter_player_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalrecord',
            name='class_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='technicalrecord',
            name='class_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True),
        ),
    ]
