# Generated by Django 4.0.4 on 2022-06-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0033_alter_technicalrecord_backhand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalrecord',
            name='class_duration',
            field=models.FloatField(default=1),
        ),
    ]
