# Generated by Django 4.0.4 on 2022-06-11 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0034_technicalrecord_class_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicalrecord',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='players', to='analysis.player'),
        ),
    ]
