# Generated by Django 4.0.4 on 2022-07-25 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0035_alter_technicalrecord_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_url', models.URLField(max_length=600)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_media', to='analysis.player')),
            ],
        ),
    ]
