# Generated by Django 4.0.4 on 2022-07-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0037_playermedia_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermedia',
            name='note',
            field=models.TextField(),
        ),
    ]
