# Generated by Django 4.0.6 on 2022-08-03 10:29

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0039_remove_playermedia_player_playermedia_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermedia',
            name='date_created',
            field=django_jalali.db.models.jDateField(auto_now_add=True, null=True),
        ),
    ]
